
version: "3.8"
services:

  mysql-slave:
    image: mysql:5.7
    container_name: mysql-slave
    network_mode: cusnet
    ports:
      - "3307:3306"
    volumes: 
      - type: bind
        source: ./mysql
        target: /etc/mysql
    restart: always
    environment: 
      MYSQL_ROOT_PASSWORD: 123456