version: "3.8"
services:

  gitbook:
    image: fellah/gitbook
    container_name: gitbook
    network_mode: cusnet
    volumes:
      - type: bind
        source: /Users/mering/projects
        target: /books/
    restart: always
    command: /bin/bash
