version: "3.8"
services:

  mongo:
    image: mongo
    container_name: mongo
    network_mode: cusnet
    ports:
      - "27017:27017"
    volumes:
      - type: bind
        source: ./db
        target: /data/db
    restart: always
