
version: "3.8"
services:

  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"
    volumes: 
      - type: bind
        source: ./config/redis.conf
        target: /usr/local/etc/redis/redis.conf
    restart: always
    command: redis-server /usr/local/etc/redis/redis.conf